### ISSUE TITLE
Update .NET Core SDK for preview 4

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor.VSCode#340]
Current issues with SDKs available right now:
- This repo is on an SDK that doesn't have up-to-date Razor component templates
- If you force the SDK to work on a 3.0 project that was created with a newer SDK you get wrong package references so you get compilation errors for the component files
- If you force the SDK to be used within OmniSharp to be the "latest" you run into an issue where you need to do `<_TargetingNETCoreApp30OrLater>true</_TargetingNETCoreApp30OrLater>` in order to get it to properly realize the 3.0 app
